Меню
OneBootcamp-1-0/ride-companion-1 pull request #20
Opened 2020-07-21 12:53 UTC by JohnC27

fixes #9

2020-07-21 20:42 UTC, o0 requested changes
1. Коммиты не атомарны. Все хранится в одном огромном коммите

2. Зачем-то вмерджены ветки. Лучше просто подмердживать мастер, потому что если работать с ветками, можно вмерджить разобранное состояние

3. Неизвестно кто решает задачу: все или один Женя. В Issue нет ответственного за задачу. Если задачу решает один Женя, где запрос на ревью от девушек?

2020-07-21 20:42 UTC, o0 commented on css/common.css
> +  line-height: 1.3;
Зачем? Не, это лишнее

2020-07-21 20:42 UTC, o0 commented on css/common.css
> +button {
Не понимаю, зачем нужен дефолтный баттон и ул, ричем еще и со сброшенными стилями. Если мы делаем дефолтный баттон, то он должен как-то выглядеть. Общие стили нужны для ситуаций, когда ты хочешь не дописывая новых стилей вставить что-то в разметку. В этой ситуации это невозможно: баттон нельзя будет отличить вообще ни от чего на сайте, как и список. Так что эти стили точно нужно убрать и, пока что, раз мы решаем задачу только меню, сделать все сбросы локально для этих блоков. И только если правила начнут повторяться несколько раз, задуматься о классе или об общем стиле.

2020-07-21 20:42 UTC, o0 commented on index.html
> +        <button type="button" class="menu-controls__btn">
Любой кнопке нужен текст, даже если он не будет виден, это требование доступности. Стоит где-то написать, что хранится в этой кнопке. Можно сделать это прямо текстом, можно через aria-атрибуты.

2020-07-21 20:42 UTC, o0 commented on index.html
> +  <div class="menu">
`div`?

2020-07-21 20:42 UTC, o0 commented on index.html
> +    <div class="menu__controls menu-controls">
Не вижу большого смысла в двух обертках. Причем, они ведут себя не слишком круто, в дизайне эти блоки неотделимы друг от друга. Меню стоит выровнять по центру. Можно в качестве референса использовать `apple.com`. При расширении, если хочется, чтобы меню занимало больше пространства, нужно занимать его через увеличение расстояния между пунктами меню.

2020-07-21 20:42 UTC, o0 commented on index.html
> +      <li><a href="#">Эконом</a></li>
Я бы не согласился с тем, что это `a`. Если используется тег `a`, то это ссылка, которая куда-то ведет, то есть у меня потенциально есть URL под результат нажатия на эту ссылку. Наше меню, фактически, работает как фильтр, так что я бы использовал тут какие-то другие активные контролы. У меня в один момент времени может быть выбран только один пункт меню. Под это есть стандартный контрол, который даже не надо будет программировать, если его правильно использовать.

2020-07-21 20:42 UTC, o0 commented on css/index.css
> +.menu-controls__btn:hover > svg {
`menu-controls__btn-icon`?

2020-07-21 20:42 UTC, o0 commented on css/index.css
> +  display: flex;
Зачем это правило? Оно, кажется, ничего даже не меняет. И почему `flex`?

2020-07-21 20:42 UTC, o0 commented on index.html
> +    <div class="menu__controls menu-controls">
Только важно помнить, что расширение должно в какой-то момент прекратиться, чтобы меню не разорвало и пункты не начали жить каждый сам по себе. Тут нужно сделать так, чтобы расстояние между пунктами не превысило среднюю ширину каждого пункта. Это примерная цифра, ее можно подобрать.

2020-07-21 20:42 UTC, o0 commented on css/index.css
> +  stroke: var(--hover-c);
`scale`? `transition`? `cursor: pointer` для консистентности?

2020-07-21 20:42 UTC, o0 commented on css/index.css
> +  overflow-x: auto;
Все пошло не так.

Всегда виден вертикальный скролл
![Annotation 2020-07-21 232055](https://user-images.githubusercontent.com/696826/88104562-47a40880-cbab-11ea-8b22-253a65c051af.png)

Горизонтальный скролл возникает при ховере
![Annotation 2020-07-21 232100](https://user-images.githubusercontent.com/696826/88104559-470b7200-cbab-11ea-8e7e-e66422456281.png)

Скроллиться должно все меню

2020-07-21 20:42 UTC, o0 commented on index.html
> +    <div class="menu__controls menu-controls">
Еще не понимаю зачем тут микс? У нас блок `menu-controls` будет использоваться отдельно где-то?

2020-07-21 20:42 UTC, o0 commented on index.html
> +  <link rel="stylesheet" href="css/index.css">
В соседнем пулреквесте у Даши `styles.css`. Ща наплодите файлов.

2020-07-23 10:18 UTC, mariaYunB approved these changes
Excellent!

2020-07-23 18:00 UTC, JohnC27 commented on index.html
> +  <link rel="stylesheet" href="css/index.css">
Выбрали Index везде

2020-07-23 20:16 UTC, o0 requested changes

2020-07-23 20:16 UTC, o0 commented on css/index.css
> +  justify-content: space-between;
Вертикальное еще выравнивание нужно сделать по центру, а то они встают по нижнему краю, а там иконки выше текста в полтора раза и смотрится странно

2020-07-23 20:16 UTC, o0 commented on index.html
> +      <input class="menu__input" id="lux" type="radio" name="menu">
luxe? luxury?

2020-07-23 20:16 UTC, o0 commented on index.html
> +      <label class="menu__label" for="economical">Эконом</label>
Дефолтное выбранное значение

2020-07-24 11:58 UTC, o0 approved these changes
Норм. Прежде чем мерджить, я советую поколдовать над компенсацией иконок, чтобы они смотрелись ровненько

2020-07-24 11:58 UTC, o0 commented on css/index.css
> +  transform: translateY(3px);
Я бы для каждой кнопки сделал уникальную оптическую компенсацию, потому что они разные по размеру.

2020-07-24 12:23 UTC, merged