Хедер и футер
OneBootcamp-1-0/ride-companion-1 pull request #21
Opened 2020-07-21 13:06 UTC by daria269

fixes #10

2020-07-21 20:12 UTC, o0 requested changes
Дополнительные замечания:

1. В PR всего один коммит, хотя задач, как минимум, две. Нужно учиться отправлять атомарные коммиты, которые решают микрозадачи. Это важно, потому что коммиты можно еще и отменять. Если я захочу откатить изменения футера, но оставить изменения хедера, у меня не получится это сделать с такими коммитами. А если бы у меня их было два, я бы смог. Атомарные коммиты это когда каждый коммит независим от другого коммита и решает ровно одну задачу.

2. Я вижу, что коммитила только Даша, но я не знаю, делает ли эту задачу она одна или нет. В самой задаче не проставлен Assignee. Нужно это обязательно сделать, чтобы я понимал. Если это делает Даша одна, значит тут обязательно должно быть еще и ревью Маши и Жени. Если эту задачу делаете вы втроем, это должно быть прозрачно.

2020-07-21 20:12 UTC, o0 commented on css/common.css
> +  --grey: #828282;
Мне не слишком нравится, что название переменной содержит название цвета. Смысл переменной в том, чтобы быть абстрактной. Типа `inactive` или `lighter` или что-то еще. Цветовая схема сайта умеет меняться, я думал о том, чтобы сделать на этом сайте переключение темной и светлой тем. В такой системе переменные должны остаться одинаковыми, а значения у них поменяться. Тогда переменная `grey` точно не подойдет.

Второе замечание по английскому. Grey это британский вариант (colour, favourite). Мне тоже британский английский нравится больше, но в разработке принято использовать американский, поэтому лучше gray (color, favorite). Это на будущее.

2020-07-21 20:12 UTC, o0 commented on css/common.css
> +  --basic-black: #000000;
Тоже самое с названием цвета в переменной.

2020-07-21 20:12 UTC, o0 commented on css/style.css
> +  background-repeat: round;
`no-repeat` наверное лучше?

2020-07-21 20:12 UTC, o0 commented on css/style.css
> +  background-size: cover;
Один из смертных грехов дизайна: скейл нефоновых картинок. Ладно, тут просто фары, это может смотреться как какой-то абстрактный градиент, но я как дизайнер могу заменить одну картинку на другую и поставить, например, тачку. А если я ее растяну, это будет смотреться как китайский дизайн. При ресайзе картинка должна не скейлиться, а у нее должно открываться больше деталей. Это значит, что лучше в этом случае экспортировать картинку побольше и обрезать ее на уровне верстки, а не экспорта.

2020-07-21 20:12 UTC, o0 commented on css/style.css
> +  display: flex;
Почему `flex`? Какие у него преимущества над `grid`? Кажется, что лучше последовательно использовать одну систему и переходить на другие только если есть реальная необходимость. Например, в фильтрах я предвижу, что уместно будет сделать `flex`. Почему тут не понимаю.

2020-07-21 20:12 UTC, o0 commented on css/style.css
> +  padding: 30px 30px 16px;
Шаг сетки 5px, поэтому не 16 а 15.

2020-07-21 20:12 UTC, o0 commented on css/style.css
> +.header__description {
Теглайн 
https://ru.wikipedia.org/wiki/%D0%A2%D1%8D%D0%B3%D0%BB%D0%B0%D0%B9%D0%BD_(%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D1%8F)

2020-07-21 20:12 UTC, o0 commented on css/style.css
> +  display: flex;
Вам хорошо на уровне команды иметь какие-то стандарты и договоренности, чтобы у вас были универсальные ответы на вопросы как вы выполняете ту или иную задачу. Вот вы работаете отдельно и у вас есть разные взгляды на мир. Одному нравится флекс, другому грид. Если вы не договоритесь, что использовать вместе, один будет использовать одно, второй второе, просто потому что нравится, удобно, привычно и так далее. Нужно сделать так, чтобы удобство не было аргументом в выборе решения, нужно сделать так, чтобы у вас были стандарты как решаются те или иные задачи.

2020-07-21 20:12 UTC, o0 commented on css/style.css
> +  display: flex;
Если кратко: почему флекс, я не пойму, хоть убей.

2020-07-21 20:12 UTC, o0 commented on index.html
> +    <img class="header__logo" src=".//img/logo.svg" width="273" height="69" alt="Cервис подписки на автомобили.">
Левый `alt`, он вообще ничего мне не объясняет о картинке. Мне то, что я на сервисе подписки на автомобили, объясняет теглайн снизу, а логотип у меня про название. И, если говорить о доступности и читаемости сайта из разметки так и не понятно, как у меня называется компания. Я тонко намекал в пулреквесте с общими стилями, как можно поступить с `h1` на странице, жаль, что я не был услышан, мне досадно повторять одни и те же рекомендации по два раза. Нужно сходить на 3lp.me и посмотреть как решен вопрос с `h1` там.

2020-07-21 20:12 UTC, o0 commented on index.html
> +    <img class="header__logo" src=".//img/logo.svg" width="273" height="69" alt="Cервис подписки на автомобили.">
А в качестве альта, думаю, стоит написать название компании.

2020-07-21 20:12 UTC, o0 commented on index.html
> +    </img>
Что. Это. Такое?

2020-07-21 20:12 UTC, o0 commented on index.html
> +    <p class="header__description">
Мы говорили на прошлом проекте о том, что начало и конец текста внутри тегов не переносится никогда. Текст должен идти сразу же после начала тега. Если это неудобно для чтения, всегда есть word wrap в редакторе. Пользователи и поисковые движки не должны отвечать за то, что у разработчика был приступ ОКР. И вообще, перенос текста в разметке трактуется как пробел. Это значит, что в начале и в конце теглайна с точки зрения браузера и поискового робота стоит по пробелу.

2020-07-21 20:12 UTC, o0 commented on index.html
> +      лучший в России сервис подписки на автомобили
Любое предложение в разметке должно быть отформатировано по правилам (точки могут быть исключениями). Это значит, что начать его нужно с большой буквы. Текст на сайте работает не только как визуальная составляющая, его можно еще и скопировать и куда-то вставить. А мне, даже если у меня, например, в меню, написано `ЛУЧШИЕ ФИЛЬМЫ`, хочется скопировать это как `Лучшие фильмы`. Разработчики CSS со мной согласны и поэтому есть отличное свойство, которое называется `text-transform`. Благодаря ему можно оставлять предложения грамотно написанными, но оформленными как угодно.

2020-07-21 20:12 UTC, o0 commented on index.html
> +    <p class="footer__text">
Все те же замечания про правила набора текстов и переносы.

2020-07-22 09:42 UTC, daria269 commented on index.html
> +      лучший в России сервис подписки на автомобили
у нас есть слово Россия, которое с большой буквы пишется. Поэтому lowercase сюда не очень подходит...
можно немножко усложнить и применить ::first-letter

2020-07-22 17:11 UTC, o0 requested changes
Прогресс

2020-07-22 17:11 UTC, o0 commented on css/common.css
> +  margin: 0;
Bold move. Зачем? Та же история с common стилями. Если я захочу встроить на эту страницу просто рандомный `p` даже без форматирования, в надежде, что он будет выглядеть нормально, то у него не должно быть отступов? Кажется, нет.

2020-07-22 17:11 UTC, o0 commented on css/index.css
> +  background-size: cover;
Мне, конечно, не совсем нравится что картинка все-таки жмется. Можем ли мы сделать так, чтобы у нас всегда были видны фары, при расширении становилось видно больше, при сужении меньше, но при этом не было ресайза?

2020-07-22 17:11 UTC, o0 commented on css/index.css
> +  background-image: url(../img/header-bg.jpg);
А чо, можно без кавычек? Я проверил в хроме, вроде работает, но интересно кроссбраузерно ли это и вообще легально ли

2020-07-22 17:11 UTC, o0 commented on index.html
> +      <a href="http://oneboot.camp/">OneBootcamp</a>
Да не нужен тут этот перенос, ну. Это же фразовый контент, он внутри строки находится и чувствительно относится к переносам в разметке. Для него это пробелы. Не нужно этого делать, серьезно. Форматирование это хорошо, но текст должен быть цельным текстом.

2020-07-22 17:11 UTC, o0 commented on css/index.css
> +.footer {
С футером лол. Сами блоки выравниваются по центру, но контент в них нет, поэтому случаются смешные казусы, если сузить окно, скажем, до `320px`. Долго делать скриншот, предлагаю проверить самостоятельно.

2020-07-22 17:11 UTC, o0 commented on index.html
> +    <h1 class="header__title">Ride companion - Лучший в России сервис подписки на автомобили.</h1>
Плюс за решение. Хвалю. Но знак препинания не тот, тут подходит длинное тире.

2020-07-23 17:05 UTC, JohnC27 commented on css/index.css
> +  margin: 12px 0 0;
Зачем верхний марджин если можно сделать у header row-gap

2020-07-24 12:01 UTC, o0 approved these changes
Все, хорошо, PR одобряю, можно мерджить, но для пущей красоты я бы добавил хедеру еще фон, который совпадает по цвету с темными краями. Тогда будет идеально

2020-07-24 13:02 UTC, merged