Блок сортировки
OneBootcamp-1-0/ride-companion-1 pull request #22
Opened 2020-07-21 13:07 UTC by daria269

fixes #11

2020-07-21 20:52 UTC, o0 requested changes
Assignee в задаче. Если делается только Дашей, где ревью остальных?

2020-07-21 20:52 UTC, o0 commented on css/common.css
> +ul {
Ребят, вам нужно согласовать вашу работу, у вас в разных PR коммитятся разные исправления в `common`. Касательно вообще `common` и `ul` я говорил в соседнем PR что это плохая идея, коммитить в `common` чистый ресет. `common` нужен для того, чтобы вставлять на всем сайте не задумываясь контент и не прописывать для него стили. Сейчас же это невозможно, потому что теперь все списки не выглядят как списки. Так что этот ресет должен быть локальным.

2020-07-21 20:52 UTC, o0 commented on index.html
> +  <header class="header">
Почему это вдруг хедер? Хедер есть в другом пулреквесте и в том хедере лого и теглайн, с ними все понятно и хорошо. Почему вот это меню это хедер, у меня вопросы.

2020-07-21 20:52 UTC, o0 commented on index.html
> +            Сначала рекомендованные
ОКР с переносами долой, объяснил в другом PR

2020-07-21 20:52 UTC, o0 commented on index.html
> +    <nav class="main-nav">
Это не `main-nav`. Это вообще не `nav`, это контрол сортировки. Так что это не `nav` ни на уровне тега, ни на уровне названия класса. Напоминаю, что блок сортировки в дизайне может стоять где угодно, хоть слева, хоть справа, хоть даже плавать снизу.

2020-07-21 20:52 UTC, o0 commented on index.html
> +      <ul class="main-nav__sort-list">
Неловкое название `sort-list`. Я вообще не уверен, что тут нужна вложенность

2020-07-21 20:52 UTC, o0 commented on index.html
> +          <a href="#">
Ссылка используется там, где есть URL на который она может вести. Нажатие на этот элемент не приводит к перезагрузке страницы или к изменению урла. Оно приводит к локальному изменению части страницы. Так что тут должен быть другой активный элемент. Какой именно? Ну, у нас несколько вариантов сортировки, но в один момент времени может быть активным только один из них

2020-07-21 20:52 UTC, o0 commented on index.html
> +          Сначала более дешевые
Ладно выше понятно, что есть ОКР с переносами текста. Но вот это уже чистая небрежность.

2020-07-21 20:56 UTC, o0 commented
Ах да, почему в названии ветки есть какой-то `list`?

2020-07-22 16:59 UTC, o0 requested changes
@mariaYunB @JohnC27 не вижу ваших комментариев

2020-07-22 16:59 UTC, o0 commented on css/index.css
> +  transform-origin: left;
Кажется, несогласованность. Почему блоки растут вправо? Кажется, лучше если просто вширь во все стороны

2020-07-22 16:59 UTC, o0 commented on css/index.css
> +.sort-list__label:active {
Ошибка. Состояние `:active` это состояние блока, пока он нажат. Нам же нужно запоминать выбранное состояние. Ну и убирать подчеркивание, про это тоже не стоит забывать. Ну и размер шрифта и начертание у активных элементов тоже нужно проверить.

2020-07-22 16:59 UTC, o0 commented on css/index.css
> +.sort-list__label:active {
Если есть сложность с тем, чтобы написать селектор для лейбла с активным инпутом, я намекну, что есть селектор `+` и псевдокласс `:checked`, но для селектора `+` важен порядок элементов в разметке, поэтому о нем тоже может быть надо будет задуматься

2020-07-22 16:59 UTC, o0 commented on css/common.css
> +  color: inherit;
Тут нужно чтобы было как в остальных PR

2020-07-22 16:59 UTC, o0 commented on css/index.css
> +  overflow: hidden;
Зачем `overflow`?

2020-07-23 17:16 UTC, JohnC27 approved these changes

2020-07-23 17:16 UTC, JohnC27 commented on css/index.css
> +
Лишняя строчка)

2020-07-24 06:27 UTC, JohnC27 commented on css/index.css
> +.sort-list__label {
Нет transition

2020-07-24 06:27 UTC, JohnC27 commented on css/index.css
> +.sort-list__input:checked + .sort-list__label {
Активный label не становиться жирным

2020-07-24 12:16 UTC, o0 requested changes

2020-07-24 12:16 UTC, o0 commented on css/index.css
> +  overflow: hidden;
@daria269 overflow не нужен, давай пожалуйста будем разбирать все комментарии

2020-07-24 12:16 UTC, o0 commented on css/index.css
> +  transform-origin: left;
Вообще ничего не резолвится, никакие комментарии. Все остается висеть

2020-07-24 12:16 UTC, o0 commented on css/index.css
> +  transform-origin: left;
`transform-origin` и `transition` конечно же должны задаваться не для состояния блока (ховер), а для всего блока. Из-за этого и происходят скачки. Точнее, это их починит, но проблема не уйдет полностью. Полностью проблема лежит в том, как блок сверстан. Но это отвлекает нас от решения задачи, поэтому нужно будет починить баг #27. Название, кстати, у него ужасное: я не пойму, что именно нужно сделать и в чем именно заключается проблема. 

Название бага должен содержать глагол (что нужно сделать), указание на место где происходит проблема и указание желаемого результата. Например: `Исправить скачки транзишна при наведении на айтемы блока сортировки`

2020-07-24 13:09 UTC, daria269 commented on css/index.css
> +  transform-origin: left;
пока не починим баг с транзишином при наведени, это останется

2020-07-24 14:12 UTC, o0 approved these changes
💪 как я не видел, что там `a` закрывающие стоят! Круто, что проблема решилась

2020-07-24 14:16 UTC, merged