Фильтры
OneBootcamp-1-0/ride-companion-1 pull request #23
Opened 2020-07-21 16:51 UTC by JohnC27

fixes #12

2020-07-21 21:14 UTC, o0 requested changes
Вижу коммиты от Маши и Жени, но не понимаю, кто решает задачу. Если Маша и Женя, где ревью от Даши?

Коммиты не атомарные. 

Отправили заведомо разобранный PR. Это, в принципе, неплохо, если вы знаете несовершенства в своем коде и обращаете на них мое внимание через комментарии. Например, если у вас есть какие-то вопросы, вы можете отправить ревью-комментарий в котором на соответствующих строчках будут ваши вопросы. 

А так я проверяю по умолчанию считая, что проверяю что-то рабочее, но, оказывается, что нет и мне, естественно, начинает казаться, что это баг.

2020-07-21 21:14 UTC, o0 commented on css/common.css
> +dd {
У вас опять какие-то загадочные глобальные стили, которые на самом деле не глобальные. В проекте со школой, у вас было много текстового контента, который потенциально формировался через админку, поэтому вам важно было сделать глобальные стили, которые можно было применять в любой точке сайта. Тут вы полностью контролируете разметку и данные у вас атомарные. У вас не может появиться два одинаковых `dd` в двух разных местах сайта, которые при этом не являются одним и тем же БЭМ-блоком. Поэтому вам не нужны глобальные стили. Если вам непонятен этот момент, попросите меня на стендапе рассказать об этом подробней.

2020-07-21 21:14 UTC, o0 commented on index.html
>    <title>Ride companion Лучший в России сервис подписки на автомобили.</title>
Блин, ну почему вы не поставили точку в `title`? Я понимаю, что я просил сделать исправление, но мне бы хотелось, чтобы вы сами думали о сайте, который делали, как о продукте, которым вы хотите пользоваться. Пока что у меня иногда создается впечатление, что вы выполняете строгое ТЗ, но не думаете о сайте с общечеловеческой, пользовательской точки зрения.

2020-07-21 21:14 UTC, o0 commented on index.html
> +      <a href="#">любой</a>
Это не ссылка, у нас нет URL который будет, когда я на этот элемент нажму. Это другой активный элемент. Какой именно, нужно сообразить.

2020-07-21 21:14 UTC, o0 commented on index.html
> +    <dd class="filter__options filter-price">
Найс, но есть замечания.

1. Нет градиента.

2. Этот блок ну никак не может называться `filter-price`, потому что блок в БЭМе это универсальная переиспользуемая вещь, а я не могу переиспользовать в других местах цену в фильтре. Я могу такой же слайдер захотеть использовать для изменения громкости музыки или для изменения масштаба карты. Я не хочу, чтобы громкость у меня менялась ценой фильтра.

3. Блок `filter-price` ну никак не может быть тегом `dd`. Этот блок может быть вложен в тег `dd`, потому что `dd` это конкретный блок в фильтрах, а блок со слайдером это универстальный переиспользуемый блок. И если тут уместно `dd`, то когда я начну ставить его как контрол звука, я не смогу использовать тег `dd`.

2020-07-21 21:14 UTC, o0 commented on css/index.css
> +  -webkit-appearance: none;
Хорошая попытка, но нет, увы, тут придется верстать все с нуля, потому что Firefox мы тоже поддерживаем и градиент нам все же нужен.

2020-07-21 21:14 UTC, o0 commented on index.html
> +      <span class="filter-price__display">от <input type="text" value="10000" class="filter-price__input"> ₽ / мес.</span>
`span`? С какого перепугу?

2020-07-21 21:14 UTC, o0 commented on css/index.css
> +  text-align: center;
Это выравнивание не работает, поэтому подпись под фильтром всегда стоит слева, а не снизу.

2020-07-21 21:14 UTC, o0 commented on css/index.css
> +  width: 100%;
Слайдер не может быть шириной в 100% вообще никогда. У меня тачскрин на Windows. Как вы представляете, что я пальцем буду перетаскивать ползунок на 13"? Это очень неудобно. Нужно задать максимальную ширину, причем очень небольшую, чтобы пользователи не уставали тащить ползунок от края до края. Максимум, пикселей 200-250

2020-07-21 21:14 UTC, o0 commented on css/index.css
> +  text-align: center;
Слайдер не выравнивается с текстом слева по центру по вертикали. Нужно это сделать.

2020-07-21 21:14 UTC, o0 commented on css/index.css
> +.filter-price__input {
Нет подчеркивания из дизайна. Ширина конская.

2020-07-21 21:14 UTC, o0 commented on index.html
> +      <span class="filter-price__display">от <input type="text" value="10000" class="filter-price__input"> ₽ / мес.</span>
`type=text`?

2020-07-21 21:14 UTC, o0 commented on index.html
> +      <span class="filter-price__display">от <input type="text" value="10000" class="filter-price__input"> ₽ / мес.</span>
Давайте зададим валидацию на поле ввода цены. Какую, пока говорить не буду, интересны ваши логические рассуждения.

2020-07-21 21:15 UTC, o0 commented on css/index.css
> +  -webkit-appearance: none;
Еще непонятно, зачем тут `input[type=range]` если вы и так используете класс. Не понимаю, какую пользу тут несет повышение специфичности селектора.

2020-07-23 20:06 UTC, o0 requested changes

2020-07-23 20:06 UTC, o0 commented on css/index.css
> +  transition: 0.2s;
JFYI вы написали `transition` на все свойства вообще, не только на `scale`, поэтому у вас плавно меняется и жирность шрифта и цвет и вообще все. На мой вкус, это избыточно. Но это просто момент осознанности, хочется, чтобы вы явно понимали, что именно тут происходит.

2020-07-23 20:06 UTC, o0 commented on css/index.css
> +  transition: 0.2s;
На мой вкус, кстати, медленный слишком. Я бы сделал в два раза быстрей.

2020-07-23 20:06 UTC, o0 commented on css/index.css
> +.filter__radio-input {
Кстати, думаю, что можно сделать тут отдельный блок, почему бы и нет.

2020-07-23 20:06 UTC, o0 commented on index.html
> +      <div class="filter__price">
Ребят, перестаньте выполнять ТЗ. Я не говорю решениями, я навожу вас на мысль, которая должна принадлежать вам. Если вам показалось, что я чего-то хочу от кода, то я ничео не хочу, у меня нет мнения, как это должно быть написано, моя задача в том, чтобы ваше мнение было полным и весомым.

2020-07-23 20:06 UTC, o0 commented on index.html
> +      <div class="filter__price">
Давайте разбирать по кускам, что именно тут происходит.

2020-07-23 20:06 UTC, o0 commented on index.html
> +      <div class="filter__price">
Первый и главный вопрос. Зачем нам враппер `filter__price`. Почему это не может быть `dd`. Да, я в прошлом ревью говорил, что `filter__price` это элемент и что он не может быть слайдером и поэтому слайдер должен быть вложен в него. Вы вложили блок со слайдером ниже. Все отлично. Зачем нужен этот `div`?

2020-07-23 20:06 UTC, o0 commented on index.html
> +        <div class="scale">
`scale` это шкала. Шкала это составная часть слайдера, поэтому блок не может называться шкалой. Это слайдер.

2020-07-23 20:06 UTC, o0 commented on index.html
> +          <div class="scale__bar"></div>
Вот этот блок вполне себе и является шкалой

2020-07-23 20:06 UTC, o0 commented on index.html
> +          <span class="scale__toggle"></span>
Toggle означает тумблер или переключатель или процесс переключения. Что именно мы можем переключить в слайдере? На что мы это можем переключить?

2020-07-23 20:06 UTC, o0 commented on index.html
> +        <div class="filter-price__display">от <input type="number" min="1" max="100000" value="10000" class="filter-price__input"> ₽ /
`display` это отображение. Отображение цены фильтра? 🤔 Ну, натянуто, я бы какое-то другое название придумал, более дескриптивное.

2020-07-23 20:06 UTC, o0 commented on index.html
> +        <div class="filter-price__display">от <input type="number" min="1" max="100000" value="10000" class="filter-price__input"> ₽ /
Говоря, что прикиньте порядки цен на машины и от этих порядков назначьте `min` и `max`, я не думал, что вы оцените, что стоимость владения машиной в месяц будет начинаться с 1 рубля и заканчиваться 10000 рублей 😢

2020-07-23 20:06 UTC, o0 commented on index.html
> +          мес.</div>
Чо за перенос?

2020-07-23 20:06 UTC, o0 commented on index.html
> +        <div class="filter-price__display">от <input type="number" min="1" max="100000" value="10000" class="filter-price__input"> ₽ /
Если говорить про валидацию, то можно добавить и `step` какой-то, потому что вряд ли у нас будет цена регулироваться с точностью до рубля. Я бы сказал, что порядок изменения цены у нас будет не меньше 1000. А то и 5000. Вряд ли у меня будет одна машина за 1 рубль, а вторая за 3 🤔

2020-07-23 20:06 UTC, o0 commented on index.html
> +      <label class="filter__label" for="car-type-any">любой</label>
У любой радоигруппы должно быть выделенное значение по умолчанию. Всегда. Когда вы делаете радиогруппу, вам обязательно нужно назначить ей дефолтное состояние.

2020-07-23 20:06 UTC, o0 commented on css/index.css
> +.filter-price__input::-webkit-outer-spin-button,
🤷 ну ладно

2020-07-24 12:12 UTC, JohnC27 commented on index.html
> +      <div class="filter-price__display">от <input type="number" min="10000" max="100000" step="5000" value="10000" class="filter-price__input"> ₽ / мес.</div>
Нет идей как назвать вместо display 🤷‍♂️

2020-07-24 12:30 UTC, o0 requested changes

2020-07-24 12:30 UTC, o0 commented on css/index.css
> +  transform: scale(1.05);
Перестал работать `transform` потому, что он по спецификации применяется только для элементов с блочной моделью https://drafts.csswg.org/css-transforms/#transformable-element

2020-07-24 12:30 UTC, o0 commented on css/index.css
> +  transform: scale(1.05);
Чтобы понять, почему он перестал работать, ищите ниже синий кружок 🔵

2020-07-24 12:30 UTC, o0 commented on index.html
> +      <div>
🔵 ПОТОМУ ЧТО ВЫ ОПЯТЬ ПОДУМАЛИ ЧТО Я ДАЛ ВАМ КОНКРЕТНУЮ ИНСТРУКЦИЮ, НЕ УТОЧНИЛИ И ПРОСТО СДЕЛАЛИ АБЫ КАК.

Ну зачем тут `div`? Когда я говорил, что имеет смысл это сделать блоком, я имел ввиду БЭМ-блок. Компонент, который можно переиспользовать. Это значит, что нужно создать отдельный класс, прописать его этому элементу. Внутри элементам тоже прописать какие-то классы. Написать какие-то стили. Сделать так, чтобы этим можно было пользоваться. Но, блин, не херачить просто бездумно дивы, просто потому что вы услышали на стендапе, что я что-то сказал.

У меня есть одна цель на этом курсе. Сделать так, чтобы вы понимали, что вы делаете. Для этого и проводятся ретроспективы, планирования, стендапы, декомпозиции и все остальное. Потому что понимание, что вы делаете это самое главное в профессии. 

Но вы часто не понимаете что вы делаете. Вы делаете или потому что я сказал, или потому что так делается, или потому что мы договорились, но вы не понимаете. У меня ровно одна просьба: не начинайте работу вообще, пока не поймете, что именно вы делаете и зачем. Иначе это заканчивается бессмысленным оборачиванием дивами. Теперь вам нужно отменить то, что вы написали и еще раз отправить мне на проверку. 

Перестаньте гадать, что я имел ввиду. Я ничего не имел ввиду. Все решения на этом буткемпе принимаете вы и я хочу, чтобы эти решения были осознанными и полными. Пока что этого не происходит и решения принимаю я, а вы не понимаете почему, но все равно делаете.

2020-07-24 12:30 UTC, o0 commented on index.html
> +      <div class="filter-price__display">от <input type="number" min="10000" max="100000" step="5000" value="10000" class="filter-price__input"> ₽ / мес.</div>
А тут вообще нужен этот элемент? Какая в нем ценность?

2020-07-24 12:30 UTC, o0 commented on index.html
> +      <div>
И блин, ребят. Вы даже не проверили все ли у вас работает перед отправкой. Ну ведь вы могли бы перед тем, как отправить пулреквест открыть браузер и сделать ховер на блоки. Вы бы тогда увидели сами, что он не работает и сами бы начали думать почему. Почему вы этого не сделали?

2020-07-24 14:17 UTC, JohnC27 commented on index.html
> +      <div class="filter-price__display">от <input type="number" min="10000" max="100000" step="5000" value="10000" class="filter-price__input"> ₽ / мес.</div>
Нам нужен этот div. Без него не выходит сгрупировать эти три элемента также хорошо как с ним

2020-07-24 14:26 UTC, o0 approved these changes
diesel и катим

2020-07-24 14:26 UTC, o0 commented on index.html
> +        <label class="filter__label" for="disel">дизель</label>
Не обратил внимание в параллельном пулреквесте. `diesel`

2020-07-24 15:32 UTC, merged