Структура данных каталога
OneBootcamp-1-0/ride-companion-1 pull request #29
Opened 2020-07-24 10:20 UTC by daria269

2020-07-24 12:44 UTC, JohnC27 commented on data.json
> +      "price": "от 75 000 ₽ / мес.",
Мы не знали может ли здесь быть не "от 75 000 Р / мес", а например, "до 500 р / _день_ ", и поэтому поместили всё в данные, если нет - то сделаем, чтобы лишь цена была в данных

2020-07-24 12:47 UTC, o0 requested changes

2020-07-24 12:47 UTC, o0 commented on data.json
> +  "cars_list": [
Можно просто `cars`, чо усложнять?

2020-07-24 12:47 UTC, o0 commented on data.json
> +      "title": "BMW 5 series",
Заголовок машины? Я думал, что у машины название, модель, название модели.

2020-07-24 12:47 UTC, o0 commented on data.json
> +{
Корневым элементом JSON может быть не только объект, но и массив. И если у вас в данных только массив, то может быть... 🤔

2020-07-24 12:47 UTC, o0 commented on data.json
> +      "price": "от 75 000 ₽ / мес.",
Ну ало, а как вы сравнивать будете? `if (price > "от 75 000 ₽ / мес.") {  }`? 
```js
"min_price": 75000
```

2020-07-24 12:47 UTC, o0 commented on data.json
> +        "characteristics": {
Выравнивание

2020-07-24 12:47 UTC, o0 commented on data.json
> +        "power": "250 л.с."
Единицу измерения долой.

2020-07-24 12:47 UTC, o0 commented on data.json
> +        "type": "седан",
Я бы все же такие данные на английском передавал. "Седан" это отображение этого типа кузова для русского языка. А чо если я на арабский переключусь?

2020-07-24 12:47 UTC, o0 commented on data.json
> +        "month": "4000",
Число строкой?

2020-07-24 12:48 UTC, o0 commented on data.json
> +      "price": "от 75 000 ₽ / мес.",
Лучше вопросы писать до того, как попросите ревью 😉

2020-07-24 14:21 UTC, o0 approved these changes
Умницы. Убрать лишнюю вложенность и можно катить. Фильтр по производителю давайте делать, ок, раз вы настаиваете. Можете просто в PR с фильтрами добавить еще одну группу фильтров, чтобы не забыть.

Ну и, если вы сегодня попробуете уже что-то поотрисовывать в DOM через JS будет очень круто.

2020-07-24 14:21 UTC, o0 commented on data.json
> +      "brand": "BMW",
Если вы решили разделить призводителя и модель, то тогда не стоит это объединять в `name`. И, таким структурированием данных, кое-кто напрашивается на отдельный фильтр по производителю, типа _посмотреть все автомобили BMW_ 😉 Ок, значит добавим 😗

2020-07-27 12:52 UTC, o0 requested changes

2020-07-27 12:52 UTC, o0 commented on data.json
> +[
Чтобы не дублировать, JSON можно прибить

2020-07-27 12:52 UTC, o0 commented on js/index.js
> +  const characteristicsRu = {
Наружу из функции, чтобы этот объект не создавался раз за разом заново.

2020-07-27 12:52 UTC, o0 commented on js/index.js
> +  }
Не забываем ставить точки с запятой. Видимо, следующим шагом, мы ставим ESLint

2020-07-27 12:52 UTC, o0 commented on js/index.js
> +  const makeImages = () => {
Выносим создание функции из функции

2020-07-27 12:52 UTC, o0 commented on js/index.js
> +const createTemplate = ({brand, model, min_price, images, mileage, characteristics}) => {
Эта функция точно не `createTemplate` а что-то вроде `createCarElement`

2020-07-27 12:52 UTC, o0 commented on js/index.js
> +const renderTemplate = () => {
У этой функции я бы сделал `data` параметром

2020-07-27 12:52 UTC, o0 commented on js/index.js
> +  const car = document.createElement('article')
Смотрите, в принципе, неплохо, но вы можете лучше. Сейчас у вас смешаны два типа создания DOM-элемента и вы сначала создаете элемент через `createElement`, добавляете ему класс, и, в качестве шаблона у вас остается только внутренняя часть. Это компромиссное решение, потому что у меня может в будущем поменяться и верхнеувровневое название тега и название класса для этого тега. Лучше будет, если в шаблонной строке будет вообще вся нужная вам разметка. Как ее вставлять в DOM? Ну, вы можете завести функцию, которая будет, например, создавать одноразовые элементы.

2020-07-27 12:52 UTC, o0 commented on js/index.js
> +  <div class="carousel">
`carousel` это отдельный от машины блок, он может использоваться и без нее. Поэтому нужно сделать под нее полностью отдельный шаблон и отрисовывать только после того, как карточка отрисовалась

2020-07-27 12:52 UTC, o0 commented on js/data.js
> +  {
Давайте сразу попробуем три машины.

2020-07-27 12:52 UTC, o0 commented on js/data.js
> +    "min_price": 75000,
Данные в JS это не JSON, поэтому можно не делать кавычек вокруг названий свойств и можно использовать camel case.

2020-07-27 12:52 UTC, o0 commented on js/data.js
> +      "half-year": 25000,
Я не знаю, как я это проглядел, но дефис в названии свойства это очень плохо, потому что это тот же символ, что и оператор минус. В названиях нужно использовать только безопасные символы, чтобы JS не сломался.

2020-07-27 12:52 UTC, o0 commented on js/index.js
> +  const makeImages = () => {
В стрелочных функциях, которые состоят из одного `return` можно не писать фигурных скобок и `return`

```js
const makeImages = () => images
  .map((img) => `<img src=${img}>`)
  .join();
```

2020-07-27 12:52 UTC, o0 commented on js/index.js
> +    return images.map((img, i) => {
`img` ➡️ `url`, `imageUrl`, `imgUrl`, `imgSrc`...

2020-07-27 12:52 UTC, o0 commented on js/index.js
> +      return `<img src="${img}" class="${i === 1 ? "" : "carousel__img"}" alt="${brand} ${model}" height="135px" width="255px">`
Ой какая логика. Но почему именно вторая картинка. Это же не устойчивый алгоритм, у вас активной может быть и сотая

2020-07-27 12:52 UTC, o0 commented on js/index.js
> +      return `<img src="${img}" class="${i === 1 ? "" : "carousel__img"}" alt="${brand} ${model}" height="135px" width="255px">`
А что если у меня всего одна картинка?

2020-07-27 12:52 UTC, o0 commented on js/data.js
> +      "./img/car-bmw.jpg",
Проверим с одной картинкой и с 10?

2020-07-27 12:52 UTC, o0 commented on js/index.js
> +    <dd class="catalog-item__milage-tariff">в месяц ${mileage.month} км,</dd>
У нас бывает, что у некоторых машин нет какого-то одного тарифа? Я бы сказал что да.

2020-07-27 12:52 UTC, o0 commented on js/index.js
> +  data.map((car) => {
`map` плохой выбор в этом случае. `map` создает новый массив и на каждой итерации из него возвращается значение. Используете вы его или нет, но массив создается, память под него выделяется. Тут лучше использовать итератор, который просто перебирает структуру, но ничего с ней не делает

2020-07-27 12:52 UTC, o0 commented on index.html
> +<script src="./js/data.js"></script>
Чо с выравниванием опять? Я не хочу искать и указывать на эти ошибки раз за разом. У нас идет шестая неделя курса, выравнивание это базовая вещь

2020-07-27 12:52 UTC, o0 commented on index.html
> +<script src="./js/data.js"></script>
Или восьмая 😲

2020-07-27 12:58 UTC, JohnC27 commented on data.json
> +[
Не поняли куда прибить.?

2020-07-27 12:59 UTC, o0 commented on data.json
> +[
💀

2020-07-27 12:59 UTC, o0 commented on data.json
> +[
🔫

2020-07-27 12:59 UTC, o0 commented on data.json
> +[
🏹

2020-07-27 13:00 UTC, o0 commented on data.json
> +[
⚔️

2020-07-27 13:00 UTC, o0 commented on data.json
> +[
❌

2020-07-27 13:11 UTC, JohnC27 commented on js/index.js
> +  }
Мы решили весь js писать в таком стиле. Можно без точек с запятой или это плохо?

2020-07-27 13:23 UTC, JohnC27 commented on js/index.js
> +      return `<img src="${img}" class="${i === 1 ? "" : "carousel__img"}" alt="${brand} ${model}" height="135px" width="255px">`
Вопрос: в слайдере на макете по бокам эта одна и та же картинка, что по средине или предыдущая и следующая

2020-07-27 13:29 UTC, o0 commented on js/index.js
> +      return `<img src="${img}" class="${i === 1 ? "" : "carousel__img"}" alt="${brand} ${model}" height="135px" width="255px">`
Ну а как ты думаешь? Зачем нужны слайдеры?

2020-07-27 13:29 UTC, JohnC27 commented on js/index.js
> +  const car = document.createElement('article')
Немного непонятно что за одноразовые элементы)

2020-07-27 13:31 UTC, o0 commented on js/index.js
> +  }
А вы на основании чего решили это делать? Просто потому что можно? Если у вас есть аргументированные обоснования, я бы их послушал. Мой опыт пока что показывает, что без точек с запятыми есть большие проблемы. Пока вы изучаете вопрос и ищете аргументы подумайте, что вернет выражение ниже и насколько это очевидно и предсказуемо

```js
let a = 1
let b = 1

a
++
b
```

2020-07-27 13:32 UTC, o0 commented on js/index.js
> +  const car = document.createElement('article')
Предлагаю в этот раз вам сначала написать код, в котором весь шаблон блока будет внутри шаблонной строки, попробовать ее вставить и тогда уже обсуждать

2020-07-27 13:33 UTC, JohnC27 commented on js/index.js
> +  <div class="carousel">
А почему именно после отрисовки? Можно же вынести карусель в отдельную функцию и во время создания машины вызывать эту функцию

2020-07-27 13:35 UTC, o0 commented on js/index.js
> +  <div class="carousel">
Ладно, мы опять сейчас перейдем к системе, где я за вас принимаю решения. Я убираю все рекоммендации и говорю только одно: карусель, это переиспользуемый блок, который может жить отдельно от карточки автомобиля

2020-07-27 14:11 UTC, JohnC27 commented on data.json
> +[
👍

2020-07-27 14:51 UTC, JohnC27 commented on js/index.js
> +  }
Мы решили не использовать точки с запятыми без определенной причины и теперь понимаем почему их лучше ставить

2020-07-28 10:15 UTC, o0 approved these changes
Убирайте `data.json` и катим, но я вам понасоздавал задач. Следующий шаг, перед тем, как вы начнете что-то делать дальше: настроить ESLint обязательно, без него не буду ничего принимать. Дальше давайте делать сортировки и фильтры, но у меня есть о чем с вами поговорить 😒

2020-07-28 10:15 UTC, o0 commented on data.json
> +[
Так а чо он все еще тут, раз мы порешили его убрать?

2020-07-28 10:15 UTC, o0 commented on css/index.css
> +  transform: translateX(0);
Ох. Проглядел момент с тем, как будет работать карусель. Ну конечно позиция задается не классом. Но в этом PR уже давайте оставим как есть

2020-07-28 10:15 UTC, o0 commented on js/data.js
> +  {
Вот сделали три машины и сразу стало видно, что в стилях у вас отступы между ними не по макету. В макете две машины стоят одна под другой, посмотрите внимательно.

2020-07-28 10:15 UTC, o0 commented on index.html
> +
Опять у вас дичь с отступами. Ну камон, мы на какой неделе буткемпа находимся. Вы кодеры с полуторамесячным стажем, ребят. Посмотрите на то, как у вас открывающий тег `ul.sort-list` выровнян. Ну серезно.

2020-07-28 10:15 UTC, o0 commented on js/index.js
> +  ${!characteristics.type ? '' : `<li>${characteristicsRu.type[characteristics.type]}</li>`}
Ну отступы же, ну!

2020-07-28 10:15 UTC, o0 commented on js/index.js
> +  </ul></article>`;
Что это за закрывающий тег `article` на одной строчке

2020-07-28 10:41 UTC, merged