Подключили ESlint и исправили ошибки
OneBootcamp-1-0/ride-companion-1 pull request #31
Opened 2020-07-28 11:43 UTC by daria269

fixes #30

2020-07-28 12:21 UTC, o0 requested changes
1. Риторический вопрос: в коммитах вы перестаёте писать "подключили", "исправили", "смотрите, какие мы молодцы", почему вы продолжаете это делать в названиях пулреквестов?

2. `Fixes according to code review` удобное, но плохое название коммита. Давайте еще раз: один коммит, одно смысловое действие. В одном коммите не стоит и косить и забивать. Мне хочется понимать, что делает код, просто глядя на `git log`, но я не могу этого сделать.

2020-07-28 12:21 UTC, o0 commented on .eslintrc.json
> +    "quotes": [2,  "double", { "allowTemplateLiterals": true }]
Смысл стандартного конфига, чтобы учиться работать по нему и не хакать его мелкими исправлениями. Отменяем все кастомные настройки и мучаемся с теми, что приехали сверху. Причем, это первый конфиг, который мы попробуем на курсе, дальше будут другие и нужно будет работать строго в соответствии с ниим.

2020-07-28 12:21 UTC, o0 commented on js/index.js
> +const renderTemplate = () => {
Ну алло, ребят, куда параметр делся? Это уже не исправление по ESLint. Внимательней.

2020-07-29 14:06 UTC, o0 requested changes
🤔

2020-07-29 14:06 UTC, o0 commented on js/index.js
> +  `<img src="${url}" class=${images.length === 1 ? `carousel__img--single` : `carousel__img`} alt="${imgAlt}" height="135px" width="255px">`
Вокруг класса нет двойных кавычек

2020-07-29 14:06 UTC, o0 commented on js/index.js
>  const createCarouselElement = (images, imgAlt) => {
Напоминаю, что в таких функциях можно не писать `return`

2020-07-29 14:06 UTC, o0 commented on js/index.js
> +  const container = document.querySelector(`.catalog`);
При каждом запуске функции вы каждый раз ищете контейнер заново. Но ведь он у вас один и тот же.

2020-07-29 14:06 UTC, o0 commented on js/index.js
> +    container.innerHTML += createCarElement(car);
Ооой. `innerHTML += `. Необязательно сразу переписывать, я хочу, чтобы вы приняли решение и порассуждали, как поступать в такой ситуации. Я сейчас просто опишу как работает то, что вы написали.

Смотрите, что происходит когда вы делаете `innerHTML +=`. У блока есть разметка. Она хранится в `innerHTML`. Запись `container.innerHTML += smth` преобразуется в `container.innerHTML = container.innerHTML + smth`. То есть, фактически, у вас получается полная перезапись контента блока. 

Чем это чревато. Вот у вас есть три картинки в блоке A, B и C. Вы, через `innerHTML += ` добавляете новую картинку D, но при этом у вас перезатираются и заново создаются и старые картинки.  То есть у вас блок становится не `A B C D`, а `new A, new B, new C, D`. При этом на картинки A, B, C могли быть добавлены обработчики, например и при перезаписи они исчезнут.

Еще одно последствие переписывания выглядит так: вы делаете перезапись блока `container` через `innerHTML` четыре раза. Получается, что фактически пока крутится этот цикл вы делаете следующее:
```
A
new A, B
another A, new B, C
yet another A, another B, new C, D
```
То есть чтобы просто добавить элемент D, вы четыре раза пересоздали заново элемент A, три раза пересоздали элемент B и два раза пересоздали C. Что будет, если вы будете создавать 100 элементов?

2020-07-29 14:08 UTC, o0 requested changes
И еще одно замечание про атомарные коммиты и пулреквесты. Какую цель выполняет этот пулреквест? Сейчас мы в нем:
1. Добавляем ESLint
2. Исправляем ошибки ESLint
3. Изменяем механизм рендеринга

Получается, что мы в этом пулреквесте из кода делаем летающий асфальтоукладчик. Нам мог бы ESLint помочь уже в соседнем пулреквесте с сортировкой, но мы не можем его выкатить, пока не исправим механизм рендеринга, который к задаче сортировки вообще никакого отношения не имеет.

Это вам на порефлексировать перед планированием следующего спринта.

2020-07-30 16:41 UTC, JohnC27 commented on js/index.js
> +    container.innerHTML += createCarElement(car);
Поняли, может тогда недочеты не связанные с eslint оставим на другой пр с фиксами, потому что по рендерингу есть пару вопросов, а eslint нужен другим веткам как вода 💧

2020-07-30 16:48 UTC, JohnC27 commented on js/index.js
> +    container.innerHTML += createCarElement(car);
Мы вообще когда создавали этот пр подразумевали что здесь будет исправление ошибок лишь по eslint, но как-то все перетекло в исправление рендера)

2020-08-04 11:10 UTC, o0 requested changes
Приведите в порядок все отступы в файле и катим, ESLint работает

2020-08-04 11:10 UTC, o0 commented on js/index.js
> +    <div class="${images.length === 1 ? `carousel__list carousel__list--single` : `carousel__list`}">
Поправьте отступы у этого блока? И вообще у всех таких. У вас два стиля:
```js
// первый
const createSomeElement = () => `<div>
  ${`Все отступы начинаются от края экрана`}
</div>`;

// второй
const createAnotherElement = () => `<div>
    ${`зачем-то сделан отступ`}
  </div>`;
```
Давайте все приведем к единому (первому, как я понимаю) стилю

2020-08-04 11:11 UTC, o0 approved these changes
Не хочу проверять второй, раз, апрув. Приведите в порядок и катим.

2020-08-04 13:02 UTC, merged