Сортировка
OneBootcamp-1-0/ride-companion-1 pull request #32
Opened 2020-07-29 10:08 UTC by mariaYunB

fixes #3

2020-07-29 14:19 UTC, o0 requested changes
Молодцы. Но в этой ветке очень не хватает ESLint. И нужно провести какую-то работу по логике

2020-07-29 14:19 UTC, o0 commented on js/sorting.js
> +radioButtons.forEach( (button) => {
Давайте завезем другой механизм подписки? У нас есть радиогруппа. У нее меняется значение. Можем ли мы, не создавая столько же обработчиков сколько у нас кнопок понять, что у нас что-то поменялось?

2020-07-29 14:19 UTC, o0 commented on js/sorting.js
> +radioButtons.forEach( (button) => {
Второй вопрос мы разберем, когда будем заниматься сохранением состояния в адресную строку и он выглядит как _нужно ли нам вообще вызывать внутри обработчика события `click` на `button` функцию `renderTemplate`_? Как нам тогда сортировать, когда у нас изменяется адресная строка браузера? Но к этому мы вернемся, просто держите в уме, что это не конечное решение.

2020-07-29 14:19 UTC, o0 commented on js/sorting.js
> +      default:
Ой, пустой дефолт. Но давайте подумаем, действительно ли нам ничего не нужно делать, когда мы не знаем какая сортировка применена? Ведь у нас есть в радиокнопках состояние по умолчанию и оно соответствует какой-то сортировке.

2020-07-29 14:19 UTC, o0 commented on js/sorting.js
> +        const newData = [...data];
Вы молодцы, что разобрались с тем, как работают сортировки и что разобрались с тем, как копировать массив и все отрисовывать. Теперь давайте разбираться с формальной логикой. `switch` это хорошая тема, у вас действительно происходят какие-то разные вещи, в зависимости от того, какое у вас состояние. 

Но почитайте ветки `switch`, которые у вас получились. В каждой из них вы:
1. Копируете массив
2. Вызываете функцию `sort`
3. Вызываете функцию `renderTemplate`

И вы это делаете всегда, вне зависимости от того, какой вариант у вас был выбран (пока оставим в сторонке дефолтный расклад). Получается, что это можно и не писать по много раз, достаточно это написать однажды и потом не переписывать, верно? И в `switch` записать только то, что действительно отличается в разных вариантах. Как думаете?

2020-07-29 14:19 UTC, o0 commented on js/sorting.js
> +        renderTemplate(data);
Не очень круто, что вы завязываетесь в этой функции на существование какой-то магической `data`. В файле она у вас нигде не объявлена. Как сделать так, чтобы у вас и `data` всегда была и при этом, чтобы она была не магической?

2020-07-29 14:55 UTC, mariaYunB commented on js/sorting.js
> +radioButtons.forEach( (button) => {
> Давайте завезем другой механизм подписки? У нас есть радиогруппа. У нее меняется значение. Можем ли мы, не создавая столько же обработчиков сколько у нас кнопок понять, что у нас что-то поменялось?

Ты имеешь в виду form?

2020-07-29 14:57 UTC, mariaYunB commented on js/sorting.js
> +        renderTemplate(data);
Как?

2020-07-29 15:05 UTC, mariaYunB commented on js/sorting.js
> +        const newData = [...data];
Думаем, что это отличная идея, но renderTemplate вызывается с разными параметрами в разных case

2020-07-29 15:52 UTC, o0 requested changes
Кстати, этот PR ждет ESLint, тут со скобками и точками с запятыми караул

2020-07-29 15:52 UTC, o0 commented on js/sorting.js
> +radioButtons.forEach( (button) => {
Ну да, это может сработать.

2020-07-29 15:52 UTC, o0 commented on js/sorting.js
> +const newData = [...data];
Давайте заново разбираться. Теперь вы создаете массив с данными только один раз. Получается, что что бы ни происходило, вы всегда перефигачиваете один и тот же массив `newData`.

2020-07-29 15:52 UTC, o0 commented on js/sorting.js
> +      renderTemplate(newData);
Теперь у вас происходит два раза `renderTemplate` просто с разными данными. Но смотрите-ка, у вас `renderTemplate` вызывается всегда, поэтому его можно не дублировать.

2020-07-29 15:52 UTC, o0 commented on js/sorting.js
> +      default:
Давайте дам больше деталей. 
1. В `switch` можно не писать `break` в некоторых `case`. В этом случае у вас произойдет "проваливание" из одного кейса в другой. 
2. Явное лучше неявного. У вас есть сортировка `recommended` но в коде она никак не отображена. Даже, если самой сортировки там нет, лучше всегда явно описать, что при ней происходит, даже если это выглядит немного избыточно.

Объединяем эти два замечания и получаем что-то вроде
```js
case `recommended`:
default:
  // что-то делаем с данными
  break;
```

2020-07-29 15:52 UTC, o0 commented on js/sorting.js
> +        newData.sort( (a, b) => {
Почти идеально, но `newData.sort` тоже повторяется. Можно сделать еще проще.

2020-07-29 15:53 UTC, o0 commented on js/sorting.js
> +        const newData = [...data];
А на мой взгляд `renderTemplate` вызывается всегда с одинаковым параметром. Просто значение этого параметра меняется в зависимости от `case`. То есть параметр один, а вот значения у него разные.

2020-07-29 15:54 UTC, o0 commented on js/sorting.js
> +        renderTemplate(data);
Ну, первым шагом можно объяснить в коде, откуда у вас берется `data`. Например, если она приехала из глобальной области видимости, можно так и написать `window.data`. Ну и когда она создается туда же ее и записать. Это будет явно. А на следующем спринте мы глубже поговорим об архитектуре коде.

2020-07-30 15:47 UTC, JohnC27 commented on js/sorting.js
> +        return false
В этом кейсе по идее надо ничего не надо менять и решили написать return false. Это ок? или есть лучший вариант, чтобы может быть sort остановить.

2020-08-04 11:25 UTC, o0 requested changes
Давайте пофиксим функциональность, после этого поговорим про стиль кода и про форматирование функций и вообще все остальное. Может быть, для этого нужно будет созвониться.

2020-08-04 11:25 UTC, o0 commented on js/sorting.js
> +        return false
Это очень плохой вариант, потому что `sort` не остановить. Щас расскажу, как работает то, что вы написали.

В JS есть такая штука как динамическое приведение типов. Это когда ты даешь в функцию одно значение, а она приводит его в тот тип, в котором она с ним может работать. Например:
```js
console.log(3 - `1`); // 2
```
Выведется двойка, потому что я использую математический оператор и все значения должны быть числовыми. Поэтому JS превратит строку `1` в число и вычтет.

Теперь к функции сортировки. Компаратор (так называется функция, которая передается в `sort`, это от английского compare, сравнивать, получается функция-сравнивальщик) всегда возвращает число. Оно может быть положительное, отрицательное или это может быть 0. Если мы возвращаем положительное, значит `a` должно стоять раньше `b`, отрицательное - наоборот и, соответственно, если 0, то `a` и `b` не меняются местами. 

Так вот, `false` при динамическом приведении типов становится нулем. Вы можете в этом убедиться сделав вот так:
```js
console.log(+false);
```
Получается, что если вы возвращаете из компаратора `false`, то вы возвращаете то, что приведется к нулю и, соответственно, сортировка не сработает, потому что все элементы останутся на месте.

**TL;DR**: если вы запустили сортировку, ее уже не остановить. Если вы не хотите сортировать, то проще будет вообще не запускать сортировку. Если же вы ее запустили, то нужно писать компаратор правильно, так, чтобы он действительно сортировал по какому-то принципу. Сейчас у вас сравнение возвращает ноль, поэтому возврата к исходному варианту не происходит (могли бы и проверить, просто запустив сортировку), вместо этого у вас так и отрисовывается последняя применившаяся сортировка.

2020-08-06 14:57 UTC, o0 approved these changes
Я понял, что про архитектуру нам с вами стоит поговорить отдельно. Что делать с внимательностью, я пока не знаю, вы забываете про банальные штуки. Но, может быть, потому что вам сложно и у вас тоннельное зрение включается. На данном этапе главное, чтобы вы понимали концепт и понимали как это работает и у вас вроде работает.

Прежде чем катить поправьте очевидное, к архитектуре и оптимизациям кода вернемся дальше

2020-08-06 14:57 UTC, o0 commented on js/sorting.js
> +  const newData = [...window.data];
Если у вас изначальный порядок теперь зашит в данных, зачем вам дублирование массива тогда? Мы его делали для того, чтобы не потерять изначальный порядок, но вы добавили `id`. Так что теперь большого смысла в дублировании нет. Важно всегда помнить зачем вам та или иная строчка кода. Потому что если вы не помните, у вас накапливается legacy. Слово, которое разработчики очень не любят.

2020-08-06 14:57 UTC, o0 commented on index.html
> +        <input type="radio" id="recommended" name="sort" class="sort-list__input">
Я дико извиняюсь. Но, кажется, у нас сортировка "сначала рекомендованные" стоит как вариант по умолчанию. Ребят, это обидный промах

2020-08-06 15:46 UTC, merged