Фильтрация
OneBootcamp-1-0/ride-companion-1 pull request #37
Opened 2020-07-30 12:26 UTC by JohnC27

fixes #4

2020-08-04 11:28 UTC, o0 requested changes
По следам утренней проверки: 
1. фильтрация не работает, нужно починить
2. меню это тоже фильтр, просто это фильтрация по категории авто
3. нужно доработать данные так, чтобы по ним можно было проверить все кейсы

Хорошо бы вмерджить в этот PR и в PR с сортировкой исправление функции отрисовки, чтобы все таки старые блоки удалялись

2020-08-04 11:32 UTC, mariaYunB commented
> По следам утренней проверки:
> 
> 1. фильтрация не работает, нужно починить
> 2. меню это тоже фильтр, просто это фильтрация по категории авто
> 3. нужно доработать данные так, чтобы по ним можно было проверить все кейсы
> 
> Хорошо бы вмерджить в этот PR и в PR с сортировкой исправление функции отрисовки, чтобы все таки старые блоки удалялись

У нас в меню нет вкладки "все" или что-то такое, как в других фильтрах, что не очень удобно, тк нужно минимум 4 раза переключиться, чтобы все посмотреть. Можно добавить?

2020-08-04 11:38 UTC, o0 commented
> У нас в меню нет вкладки "все" или что-то такое, как в других фильтрах, что не очень удобно, тк нужно минимум 4 раза переключиться, чтобы все посмотреть. Можно добавить?

Очень правильный вопрос. Дам ответ продакт-менеджера: пользователям это не нужно, они всегда ищут в конкретном сегменте. Для перехода в соседний нужна мотивация. Если мне нужна эконом тачка, вряд ли я, если ее не найдется, пойду искать люкс-тачку. В обратную сторону то же самое. Если я не могу взять Мерс и я хочу взять Мерс, то я не уверен, что хочу вместо Мерса брать Солярис, пацаны не поймут.

2020-08-04 12:20 UTC, mariaYunB commented
> Очень правильный вопрос.

Не думаю, что все знают, чего они хотят. Это вряд ли относится к эконому/люксу, но если взять соседние ценовые категории — найдутся те, кто потенциально мог бы заплатить (чуть) больше, но ему не показали варианты, а самому тыкать лень. Или нет?

2020-08-04 12:32 UTC, o0 commented
> Не думаю, что все знают, чего они хотят. Это вряд ли относится к эконому/люксу, но если взять соседние ценовые категории — найдутся те, кто потенциально мог бы заплатить (чуть) больше, но ему не показали варианты, а самому тыкать лень.

Согласен, что переход между соседними категориями будет производиться чаще, это правда. Но даже в этом случае важно, чтобы переход был осознанным, чтобы это был выбор человека заплатить побольше, а не приложение ему это навязывало. Это как в том анекдоте про то, что _у нас туалетной бумаги нет, но вот есть отличная наждачка_. Важно не перейти эту грань. Я согласен что надо всячески идти на поводу у пользовательской лени, но в какой-то момент важно все же заставить пользователя перешагнуть через лень и принять решение, а не делать это за него. Когда вопрос касается повышения цены, это хороший сценарий. Мы можем его подталкивать к этому решению, например, в самом низу списка или на странице неудачной фильтрации предлагать ему поискать в другой категории, но решение все же должно оставаться за ним

2020-08-04 14:37 UTC, o0 requested changes
Пока написал высокоуровнево. Если что, мы сможем созвониться и обсудить детально.

2020-08-04 14:37 UTC, o0 commented on index.html
> +        </div>
Ну опять, опять какая-то херня с отступами и переносами. Что это за закрывающий див, ребят, ну не смешно, только сегодня об этом говорили.

2020-08-04 14:37 UTC, o0 commented on js/data.js
> +    class: 'economical'
`economy`?

2020-08-04 14:37 UTC, o0 commented on js/data.js
> +      engine: 'petrol',
Harry Potter, cup of tea, bloody hell. 

Минутка осознанности. `petrol` это британская версия, американская это `gas` (`gasoline`). В мире в целом и в мире разработчиков в частности более распространен американский английский, это тоже нужно учитывать. Например, поэтому свойство в CSS назвается `color` а не `colour`.

2020-08-04 14:37 UTC, o0 commented on js/filtration.js
> +let carClassActiveOption = `economical`;
Давайте эти значения брать со страницы? Сейчас у вас производится дублирование начального состояния в HTML и в JS. Если я поменяю это в одном месте, мне нужно будет менять и в другом. Лучше просто завязаться на что-то одно. Если вы доверяете JS, то тогда после загрузки страницы, вам нужно будет сразу же выставить состояние фильтров в разметке в соответствии переменным в JS. Если вы доверяете HTML, то наоборот.

2020-08-04 14:37 UTC, o0 commented on js/filtration.js
> +  carClassActiveOption = e.target.id;
Один и тот же код внутри разных обработчиков. Это плохо. Если код идентичный, то это одна и та же функция. Или код должен быть разным.

2020-08-04 14:37 UTC, o0 commented on js/filtration.js
> +const filterData = () => window.data.filter((car) => {
Очень сложная функция. Такую неудобно поддерживать. У меня может меняться количество фильтров на странице. Например, мы с вами можем договориться отключить какой-то один. Если мы это сделаем, то нам придется переписывать не только обработчик в форме, но и эту сложную функцию. Давайте сделаем так, чтобы нам не пришлось этого делать и под разные варианты фильтрации, у нас были разные функции фильтрации.

2020-08-04 14:37 UTC, o0 commented on js/range.js
> +  const fill = slider.value * 100 / maxValue;
Мне не нравится что тут есть слайдер, потому что это абстрактный компонент, по идее. Но ладно, что есть то есть. Просто теперь у нас может не покатиться фильтрация (ценность для пользователя) из-за того, что у нас не синхронизируется бэкграунд в слайдере (другая ценность для пользователя). Все опять намешано в кучу

2020-08-04 14:37 UTC, o0 commented on js/filtration.js
> +let carClassActiveOption = `economical`;
Глобальные переменные это не очень хороший паттерн, лучше стараться сделать функции, у которых есть параметры

2020-08-06 15:12 UTC, o0 requested changes
Почти дожали

2020-08-06 15:12 UTC, o0 commented on js/filtration.js
> +    if (e.target.name !== `price`) {
Недогуглили. Вы можете пойти в две стороны для того, чтобы нормально получить информацию о том, какой инпут чекнут. 
1️⃣ У инпутов хорошо использовать атрибут `name`
2️⃣ Если лень использовать `name` или непонятно, как это делается, у вас есть псевдокласс `:checked`. 

Вы правильно рассудили, что нужно искать чекнутый инпут, но `[checked]` это отмеченный на уровне разметки, а `:checked` это отмеченный прямо сейчас. К сожалению, такое расхождение есть. В таком случае лучше всего с этим просто жить и не пытаться подогнать разметку под это дело, потому что любое переколбашивание атрибутов это дополнительная перерисовка дом-дерева. И у вас фактически получается при каждом чеке радиобатона дважды перерисовывается дом. И только для того, чтобы вам было удобней искать активный элемент.

2020-08-06 15:12 UTC, o0 commented on js/range.js
> +    slider.style.backgroundSize = `calc(${100 - fill}% + 9px) 100%`;
Я все это время не вдавался в подробности этого кода, вот обратил внимание. У вас абсолютно идентичная формула в двух ветках `if/else` за исключением одного маленького значения. Получается, что в зависимости от условия, у вас меняется ровно это значение. Как в JS описать зависимость одного значения от условия? Не ветки логики, как у вас сейчас, а одного значения.

2020-08-06 17:48 UTC, o0 approved these changes
Насколько же вы сильно экономите усилия, други мои 😉

2020-08-07 09:26 UTC, merged