Скачивание данных и уведомления
OneBootcamp-1-0/ride-companion-1 pull request #49
Opened 2020-08-14 14:57 UTC by mariaYunB

fixes #6

2020-08-17 15:12 UTC, o0 requested changes

2020-08-17 15:12 UTC, o0 commented on index.html
> +  <section class="loading-notification alert">
Я думаю, что это сообщение это часть каталога

2020-08-17 15:12 UTC, o0 commented on js/filtration.js
> +  window.carsDataCopy = filteredData;
Внутри этой функции два раза перезаписывается `window.carsDataCopy`. В этом нет никакого смысла, потому что после работы функции останется результат только второй перезаписи.

2020-08-17 15:12 UTC, o0 commented on js/getData.js
> +.then((res) => res.json())
Странное выравнивание

2020-08-17 15:12 UTC, o0 commented on js/getData.js
> +.then((data) => data);
Вот эта функция не делает ничего вообще.

2020-08-17 15:12 UTC, o0 commented on js/index.js
> +    container.before(createAlert(`section`, `error-notification notification alert`, `<h2 class="error-notification__title">¯\\_(ツ)_/¯ Слишком строгие фильтры</h2>
Вот этот блок может появляться по сто раз на дню, а мы его постоянно то создаем то удаляем. Может быть лучше будет переиспользовать?

2020-08-17 15:12 UTC, o0 commented on js/index.js
> +const deleteAlerts = () => {
Странная функция. Зачем мне удалять вообще все сообщения об ошибках?

2020-08-17 15:12 UTC, o0 commented on js/index.js
> +const createAlert = (wrapper, wrapperClass, content) => {
Мы говорили об абстрактных функциях. Эта называется `createAlert`, но при этом она умеет создавать вообще любые элементы. Может быть ее стоит назвать иначе?

2020-08-17 15:12 UTC, o0 commented on js/index.js
> +const createAlert = (wrapper, wrapperClass, content) => {
Еще непонятно, зачем разбивать создание элемента на два этапа. Сначала вы через `document.createElement` создаете обертку, а потом с помощью `innerHTML` создаете все внутренние элементы. Почему вы не создаете сразу все через разметку? Представьте, что у вас в команде работает верстальщик, который не знает JS и ему поручено перенести в JS шаблоны. Он не сможет затащить в него контейнеры.

2020-08-17 15:12 UTC, o0 commented on js/index.js
> +    if (!navigator.onLine) {
https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/Online_and_offline_events

2020-08-17 15:12 UTC, o0 commented on js/sorting.js
> +  const checkedInputId = document.querySelector(`input[name=sort]:checked`).id;
Better

2020-08-17 15:12 UTC, o0 commented on js/index.js
> +      container.before(createAlert(`section`, `error-notification notification alert`, `<h2 class="error-notification__title">¯\\_(ツ)_/¯ Что-то пошло не так</h2>
Fun fact. 404 ошибка не попадает в `catch`, она обрабатывается в `then`

2020-08-17 15:12 UTC, o0 commented on js/index.js
> +    const filteredData = window.filterAll(data);
Зачем тут эта константа, она же используется только один раз?

2020-08-19 12:32 UTC, o0 requested changes
Код получился немного спагетти, но давайте его перепишем уже в рамках рефакторинга. Сделайте нормальный алерт про офлайн, а потом уже в другом пулреквесте будем распутывать

2020-08-19 12:32 UTC, o0 commented on js/index.js
> +const createElement = (html) => {
Да здравствует копипаст. Даже пустую строку и ту стащили 👀

2020-08-19 12:32 UTC, o0 commented on js/index.js
> +const createElement = (html) => {
Тогда контрольный вопрос. Что такое `template.content`

2020-08-19 14:20 UTC, mariaYunB commented on js/index.js
> +const createElement = (html) => {
#document-fragment ?

2020-08-19 15:40 UTC, o0 commented on js/index.js
> +const createElement = (html) => {
А что такое documentFragment?

2020-08-19 15:41 UTC, o0 approved these changes
Катим

2020-08-19 18:49 UTC, merged